server:
  port: 8083
spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: stock-service
  datasource:
    url: jdbc:mysql://mysql-stock:3306/stock_db
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/