server:
  port: 8082
spring:
  config:
    import: optional:file:./.env[.properties]
  application:
    name: storage-service
  datasource:
    url: jdbc:mysql://localhost:3306/storage_db
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
