server:
  port: 8084
spring:
  application:
    name: headquarters-service
  datasource:
    url: jdbc:mysql://localhost:3306/headquarters_db
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/