server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/user/**
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/api/product/**
        - id: stock-service
          uri: lb://stock-service
          predicates:
            - Path=/api/stock/**
        - id: storage-service
          uri: lb://storage-service
          predicates:
            - Path=/api/storage/**
        - id: movements-service
          uri: lb://movements-service
          predicates:
            - Path=/api/movements/**
        - id: headquarters-service
          uri: lb://headquarters-service
          predicates:
            - Path=/api/headquarters/**
        - id: report-service
          uri: lb://report-service
          predicates:
            - Path=/api/report/**



eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    root: info
    org.springframework.cloud.gateway.route.RouteDefinitionLocator: info
    org.springframework.cloud.gateway: TRACE
