server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/credentials/**
          filters:
            - RewritePath=/api/credentials/actuator/(?<segment>.*), /actuator/${segment}
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/api/products/** , /api/batches/** , /api/categories/**
          filters:
            - RewritePath=/api/products/actuator/(?<segment>.*), /actuator/${segment}
        - id: stock-service
          uri: lb://stock-service
          predicates:
            - Path=/api/stock/**
          filters:
            - RewritePath=/api/stock/actuator/(?<segment>.*), /actuator/${segment}
        - id: storage-service
          uri: lb://storage-service
          predicates:
            - Path=/api/storage/**
          filters:
            - RewritePath=/api/storage/actuator/(?<segment>.*), /actuator/${segment}
        - id: movements-service
          uri: lb://movements-service
          predicates:
            - Path=/api/movements/**
          filters:
            - RewritePath=/api/movements/actuator/(?<segment>.*), /actuator/${segment}
        - id: headquarters-service
          uri: lb://headquarters-service
          predicates:
            - Path=/api/headquarters/**
          filters:
            - RewritePath=/api/headquarters/actuator/(?<segment>.*), /actuator/${segment}
        - id: report-service
          uri: lb://report-service
          predicates:
            - Path=/api/report/**
          filters:
            - RewritePath=/api/report/actuator/(?<segment>.*), /actuator/${segment}
      default-filters:
        - AddRequestHeader=X-Gateway-Auth, gateway-secret





eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    root: info
    org.springframework.cloud.gateway.route.RouteDefinitionLocator: info
    org.springframework.cloud.gateway: TRACE
